#!/system/bin/sh
#
# Copyright 2023 shadow3aaa@gitbub.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
MODDIR=${0%/*}
LOCALE=$(getprop ro.product.locale)
EXTENSIONS=/dev/fas_rs/extensions
MOD_EXTENSIONS=/data/adb/fas-rs/extensions

if [ -z $LOCALE ]; then
    LOCALE=$(cat "$MODDIR/LOCALE")
fi

local_print() {
	if [ $LOCALE = zh-CN ]; then
		echo "$1"
	else
		echo "$2"
	fi
}

key_check() {
    while true; do
        key_check=$(/system/bin/getevent -qlc 1)
        key_event=$(echo "$key_check" | awk '{ print $3 }' | grep 'KEY_')
        key_status=$(echo "$key_check" | awk '{ print $4 }')
        if [[ "$key_event" == *"KEY_"* && "$key_status" == "DOWN" ]]; then
            keycheck="$key_event"
            break
        fi
    done
    while true; do
        key_check=$(/system/bin/getevent -qlc 1)
        key_event=$(echo "$key_check" | awk '{ print $3 }' | grep 'KEY_')
        key_status=$(echo "$key_check" | awk '{ print $4 }')
        if [[ "$key_event" == *"KEY_"* && "$key_status" == "UP" ]]; then
            break
        fi
    done
}

if [ -f "/data/adb/fas-rs/fas-rs-mod-installed" ]; then
    for file in $MOD_EXTENSIONS/*offset*.lua; do
        if [ -f "$file" ]; then
            local_print "- 检测到冲突插件：$file" "- Conflict extension detected: $file"
        fi
    done
    for file in $MOD_EXTENSIONS/*extra*.lua; do
        if [ -f "$file" ]; then
            local_print "- 检测到冲突插件：$file" "- Conflict extension detected: $file"
        fi
    done
    if [ -f $MOD_EXTENSIONS/fas_gt_DLC.lua ]; then
        local_print "- 检测到冲突插件：fas_gt_DLC.lua" "- Conflict extension detected: fas_gt_DLC.lua"
    fi
    if [ -f $MOD_EXTENSIONS/fas_ext.lua ]; then
        local_print "- 检测到冲突插件：fas_ext.lua" "- Conflict extension detected: fas_ext.lua"
    fi
else
    for file in $EXTENSIONS/*offset*.lua; do
        if [ -f "$file" ]; then
            local_print "- 检测到冲突插件：$file" "- Conflict extension detected: $file"
        fi
    done
    for file in $MOD_EXTENSIONS/*extra*.lua; do
        if [ -f "$file" ]; then
            local_print "- 检测到冲突插件：$file" "- Conflict extension detected: $file"
        fi
    done
    if [ -f $EXTENSIONS/fas_gt_DLC.lua ]; then
        local_print "- 检测到冲突插件：fas_gt_DLC.lua" "- Conflict extension detected: fas_gt_DLC.lua"
    fi
    if [ -f $EXTENSIONS/fas_ext.lua ]; then
        local_print "- 检测到冲突插件：fas_ext.lua" "- Conflict extension detected: fas_ext.lua"
    fi
fi

echo "- Done"

sleep 5
